{% set version = "1.0.1" %}
{% set name = "songbird" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dd762ff871a6d69da9e6536ab4cdbc6027f3e50234c0c659f18470310046a8e


build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

  entry_points:
    - qiime2.plugins = songbird.q2.plugin_setup:plugin

requirements:
  host:
    - python <3.7
    - pip
    - numpy >=1.13.1

  run:
    - python <3.7
    - ipython
    - pandas
    - click
    - tensorflow ==1.14.0
    - numpy >1.13
    - scikit-bio >0.5.4
    - nose >=1.3.7
    - seaborn
    - patsy
    - scikit-learn
    - tqdm
    - h5py
    - biom-format
    - mock
    - google-pasta

test:
  imports:
    - songbird

about:
  home: https://github.com/biocore/songbird
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Vanilla regression methods for microbiome differential abundance analysis'

extra:
  recipe-maintainers:
    - mortonjt
