{% set version = "1.0.3" %}
{% set name = "songbird" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1bc374eb8188ef13934a1f4d1df3183d0819e95d434f0c53e6333eda5865074


build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

  entry_points:
    - qiime2.plugins = songbird.q2.plugin_setup:plugin

requirements:
  host:
    - python
    - pip
    - numpy >=1.13.1

  run:
    - python
    - pandas <1.0
    - click
    - tensorflow >=1.15,<2
    - numpy >1.13
    - scikit-bio >0.5.4
    - patsy
    - tqdm
    - h5py
    - biom-format

test:
  imports:
    - songbird

about:
  home: https://github.com/biocore/songbird
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Vanilla regression methods for microbiome differential abundance analysis

extra:
  recipe-maintainers:
    - mortonjt
