travis:
  secure:
    BINSTAR_TOKEN: RZDA7JSAmjXg5bXWoj86TR2mtWk3/adwQy24IoHXs2kQoseb7WiLHeLFpsPR33s+8kCQkr9LvBeRsqfW391Qunx9Tg/h6EW60FdiUQkXa0SbaFxurFKDAK9o+D0lj+qcInyt7nkkpqmlEAYTHajg6vlwZieMJY321ZNSp5gOTZBKZREohNwAz8oJWr4/fD7dsBfPiAqPpNUlcGDyiGX5R8rYnDJHZws8J0K26zm8s5U4Hh6SNZA4AD6cUmr0e5NhK5p9xip03zgIkEoZyPUA7p+u6eQXgiwRCRbZwQL93CyNMYGmzSOUSxjrEIm0s5GD0kfzESJYNjPt1qABygVcx04qnODzOkjkTbPeVpJ9OvCBmdgOmsohHIdWga8H9LG6kAxDhIUfCvyDabwFqZ5Xm/9aXjDDN99Rm9ksfF4nNXcNL7ogCWs5AFJWihkMPE7pZeQM8UY7rn5dDoqYicOUKapvjkQY/KjceXlNs+SxIbATHi6O1WFwkCOU7XieqNmiGXkttUmc1/iiy7kVCWEq0pJoy0RkiSNjf3ghLe1auogEKT42RT7P6SXh8HZTusUNzGoWCaE3vTl4IRsRd56WP5TXibFZj9gwsVpDDRQMcmUwG0zQI4AMhLnhYV7Ybp4WpBgbgbw21cLpEViThZm2ujHvxOjUfl1RMQ62QVxKsAs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
