travis:
  secure:
    BINSTAR_TOKEN: iknZHizDLv9aL9+tIoRlSYmcoc3bEh1SH7u5TY3Ego97d2TcldHNm2JPya8tUQD0kLR41NPav9gUJDmF42goCRSJ+w3msh47jxqEN/0X+nIQbxIcA7L+QJ1pyRS9U6KcUByFVzSxOxTgC7tkDhDdMT/FLLGMeXrN71Od5tjoHHu81NcmRKydHaqbRUQALjaqM9+ytRdfV4CQ+lOkZz/6YOoK/RTgRpKc1LiPbXDK+e8efbs3f4NqOwWOuKTLphCK1OUjVBHwgnwOMaoN7htDERrkQJZBUtvaklEMdLz/D0ilP5M7JitJa3PyjLGyRyholOvqGTSy4E8K+/x6GxHtVHtki1KjVfmVUIbP87Y0p8GhUE5OHdPRUrWMHlj3Rf6t8Kqs5Zb17xW2RdPU/KP5dD33O7jGt4BgjGmMH1tS8RdlM1yU/RP6uQhdJbXJ2KcSUQsgUq40YU4pCI3b505PWIdZZw6ZqM/49GPHBrAd7Ej7hle9JHpFLNqrS3rhcVyVBPBhOvfSBhbOU4Aw0cpRWrS2j9bxytjMElSRxJFde2hUnscdv2rJBphJuVnCmxE/TyxZL6BBQ7GmrWzVGDnFv5HVoETI/0TrjTgc7KWUo6tUdBEcynbBuDg4vUuF9DUSHzVyG9eOIsnwu3vNsn/AZFBqdLdgkOMrwy0qEc3Y0yY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
