travis:
  secure:
    BINSTAR_TOKEN: EmFrjhrOV/164GY9CdObKRGvNJXLWIQnii8IT8hu2JQi67NaVeuGYABGJRLTMq1n1y+N2DIIxLW4sMdozInY/DpOg/fDUHX8tN4C7ukif5G31FRGJ2FdQqlNW8eFb71cHsAFzUM32i2W/kCnq2sJIpMml3tNUa2dScrlQYOgIauAzJ8O7jPydPSuRXy5INGCt33klQI2PG5ygi8nXdZfm/ZWpbm8Dap0wV85LnMfuoiJj/+wayPnkDp2C7D73kqQ1QS5/o1u/AxNiEGaupju3hZWMYO/tdCvN2/P9VO+lj2KTHCADkJSqfyCarVXKLcrIgFnsrSiOS25h5gKludJw0/cAZbGY1zN55bj3tBeX+DxPi5HORcxmMM0Zh0Dj0S3u0PznK43iLku0kvUn+3OtzZpoOCcQaTafxiMy4pVA1bs2VazFFU4f2lKLARPdQbqSllwsayAS2ZIgHSl/y73tmeZ0KbsaWl4cz79yuipn73m+uomrbYi8iEq0e4hmyfwcHIWD6fqn1xqAGTRCWXojmooUZ6dRyXA2gwTG+GAA546xjfQGfrHf36Qa0yWWK8dduN4Q+nAc2uou44+jLfFbizMwPpr4t7X1TySaCw1RA4F9sqdEIr3qg1zmnLZ0H0sV4/6KkFM/ilPRCZrmyVIG/+uqbc0rquhcqXmwYFctUE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
